require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'infra/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Layout/LineLength:
  Max: 160
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 8

RSpec/NestedGroups:
  Max: 4

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/tasks/**/*'

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Lint/DuplicateBranch:
  Exclude:
    - 'app/services/result_parsers/**/*'
